version: '3.8'

services:
  apache:
    image: httpd:latest
    container_name: apache_web
    ports:
      - "8080:80"  # Mapea el puerto 8080 del host al puerto 80 del contenedor
    volumes:
      - ./public_html:/usr/local/apache2/htdocs  # Monta el directorio local `public_html` al directorio raíz de Apache en el contenedor
    restart: always

